/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author shrey
 */
public class DisplayReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayReportJPanel
     */
    Person person;
    Driver driver;
    VehicleRegistration vehicleInfo;
    Patient patient;
    Doctor doctor;
    Insurance insurance;
    Address address;

    public DisplayReportJPanel(Person person, Address address, Driver driver, VehicleRegistration vehicleInfo, Patient patient, Doctor doctor, Insurance insurance) {
        initComponents();
        this.person = person;
        this.driver = driver;
        this.vehicleInfo = vehicleInfo;
        this.patient = patient;
        this.doctor = doctor;
        this.insurance = insurance;
        this.address = address;
        displayPersonInfo(); //To display person information
        displayDriverInfo(); //To display driver information
        displayVehicleInfo(); //To display Vehicle information
        displayPatientInfo(); //To display patient information
        displayDoctorInfo(); //To display doctor information
        displayInsuranceInfo(); //To display insurance information
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personalInformationJPanel = new javax.swing.JPanel();
        bloodTypeTx = new javax.swing.JTextField();
        occupationlbl = new javax.swing.JLabel();
        firstNamelbl = new javax.swing.JLabel();
        phoneNumberlbl = new javax.swing.JLabel();
        ageTx = new javax.swing.JTextField();
        phoneNumberTx = new javax.swing.JTextField();
        SSNlbl = new javax.swing.JLabel();
        firstNametx = new javax.swing.JTextField();
        lastNamelbl = new javax.swing.JLabel();
        SSNTx = new javax.swing.JTextField();
        lastNameTx = new javax.swing.JTextField();
        passportlbl = new javax.swing.JLabel();
        bloodTypelbl = new javax.swing.JLabel();
        occupationTx = new javax.swing.JTextField();
        agelbl = new javax.swing.JLabel();
        passportTx = new javax.swing.JTextField();
        educationPersonlbl = new javax.swing.JLabel();
        educationPersonTx = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbylbl = new javax.swing.JLabel();
        hobbyTx = new javax.swing.JTextField();
        VehicleJPanel = new javax.swing.JPanel();
        ownerNameTx = new javax.swing.JTextField();
        registrationNumberlbl = new javax.swing.JLabel();
        modelNameTx = new javax.swing.JTextField();
        serialNumberTx = new javax.swing.JTextField();
        registrationNumberTx = new javax.swing.JTextField();
        serialNumberlbl = new javax.swing.JLabel();
        modelNamelbl = new javax.swing.JLabel();
        yearlbl = new javax.swing.JLabel();
        yearTx = new javax.swing.JTextField();
        ownerNamelbl = new javax.swing.JLabel();
        DoctorJPanel = new javax.swing.JPanel();
        annualIncomelbl = new javax.swing.JLabel();
        workcityTx = new javax.swing.JTextField();
        educationTx = new javax.swing.JTextField();
        annualIncomeTx = new javax.swing.JTextField();
        doctorIDTx = new javax.swing.JTextField();
        specializationTx = new javax.swing.JTextField();
        nameTx1 = new javax.swing.JTextField();
        doctorIDlbl = new javax.swing.JLabel();
        namelbl1 = new javax.swing.JLabel();
        educationlbl = new javax.swing.JLabel();
        workcitylbl = new javax.swing.JLabel();
        Specializationlbl = new javax.swing.JLabel();
        feebl = new javax.swing.JLabel();
        feeTx = new javax.swing.JTextField();
        PatientJPanel = new javax.swing.JPanel();
        patientIDlbl1 = new javax.swing.JLabel();
        primaryDoctorTx1 = new javax.swing.JTextField();
        patientIDTx1 = new javax.swing.JTextField();
        primaryDoctorlbl1 = new javax.swing.JLabel();
        lastVisitDatelbl1 = new javax.swing.JLabel();
        nextAppointmentDatelbl1 = new javax.swing.JLabel();
        onMedicationYesRb1 = new javax.swing.JRadioButton();
        allergieslbl1 = new javax.swing.JLabel();
        allergiesNoRb1 = new javax.swing.JRadioButton();
        onMedicationlbl1 = new javax.swing.JLabel();
        onMedicationNoRb1 = new javax.swing.JRadioButton();
        allergiesYesRb1 = new javax.swing.JRadioButton();
        LastVisitDate = new com.toedter.calendar.JDateChooser();
        NewAppointmentDate = new com.toedter.calendar.JDateChooser();
        InsuranceJPanel = new javax.swing.JPanel();
        locationTx = new javax.swing.JTextField();
        deductibleTx = new javax.swing.JTextField();
        insuranceTx = new javax.swing.JTextField();
        locationlbl = new javax.swing.JLabel();
        insuranceID = new javax.swing.JLabel();
        installationlbl = new javax.swing.JLabel();
        statementlbl = new javax.swing.JLabel();
        deductiblelbl = new javax.swing.JLabel();
        statementTx = new javax.swing.JTextField();
        installmentTx = new javax.swing.JTextField();
        DriverJPanel = new javax.swing.JPanel();
        licenselbl = new javax.swing.JLabel();
        licenseNumberTx = new javax.swing.JTextField();
        addressJPanel = new javax.swing.JPanel();
        GPSLocationlbl4 = new javax.swing.JLabel();
        GPSLocationTx4 = new javax.swing.JTextField();
        citylbl4 = new javax.swing.JLabel();
        cityTx4 = new javax.swing.JTextField();
        statelbl4 = new javax.swing.JLabel();
        stateTx4 = new javax.swing.JTextField();
        countrylbl4 = new javax.swing.JLabel();
        countryTx4 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        personalInformationJPanel.setBackground(new java.awt.Color(255, 255, 255));
        personalInformationJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Personal Information\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        personalInformationJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        personalInformationJPanel.add(bloodTypeTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 238, -1));

        occupationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        occupationlbl.setText("Occupation");
        personalInformationJPanel.add(occupationlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        firstNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        firstNamelbl.setText("First Name");
        personalInformationJPanel.add(firstNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 109, 24));

        phoneNumberlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        phoneNumberlbl.setText("Phone Number");
        personalInformationJPanel.add(phoneNumberlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        personalInformationJPanel.add(ageTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 238, -1));
        personalInformationJPanel.add(phoneNumberTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 240, -1));

        SSNlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        SSNlbl.setText("Social Security Number ");
        personalInformationJPanel.add(SSNlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        firstNametx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNametxActionPerformed(evt);
            }
        });
        personalInformationJPanel.add(firstNametx, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 240, -1));

        lastNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastNamelbl.setText("Last Name");
        personalInformationJPanel.add(lastNamelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, 20));
        personalInformationJPanel.add(SSNTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 240, -1));
        personalInformationJPanel.add(lastNameTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 240, -1));

        passportlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        passportlbl.setText("Passport Number");
        personalInformationJPanel.add(passportlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        bloodTypelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        bloodTypelbl.setText(" Blood Type");
        personalInformationJPanel.add(bloodTypelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, -1, -1));
        personalInformationJPanel.add(occupationTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 238, -1));

        agelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        agelbl.setText("Age");
        personalInformationJPanel.add(agelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 50, -1, -1));
        personalInformationJPanel.add(passportTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 238, -1));

        educationPersonlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        educationPersonlbl.setText("Education");
        personalInformationJPanel.add(educationPersonlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        educationPersonTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                educationPersonTxActionPerformed(evt);
            }
        });
        personalInformationJPanel.add(educationPersonTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 240, -1));
        personalInformationJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, -1, -1));

        hobbylbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        hobbylbl.setText("Hobby");
        personalInformationJPanel.add(hobbylbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        hobbyTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hobbyTxActionPerformed(evt);
            }
        });
        personalInformationJPanel.add(hobbyTx, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 240, -1));

        VehicleJPanel.setBackground(new java.awt.Color(255, 255, 255));
        VehicleJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Vehicle Registration Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        registrationNumberlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        registrationNumberlbl.setText("Registration Number");

        registrationNumberTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationNumberTxActionPerformed(evt);
            }
        });

        serialNumberlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        serialNumberlbl.setText("Serial Number ");

        modelNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        modelNamelbl.setText("Model Name");

        yearlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        yearlbl.setText("Year");

        ownerNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ownerNamelbl.setText("Owner Name");

        javax.swing.GroupLayout VehicleJPanelLayout = new javax.swing.GroupLayout(VehicleJPanel);
        VehicleJPanel.setLayout(VehicleJPanelLayout);
        VehicleJPanelLayout.setHorizontalGroup(
            VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VehicleJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registrationNumberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelNamelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(modelNameTx, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(registrationNumberTx))
                .addGap(64, 64, 64)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serialNumberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(VehicleJPanelLayout.createSequentialGroup()
                        .addComponent(serialNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(ownerNamelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ownerNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VehicleJPanelLayout.setVerticalGroup(
            VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VehicleJPanelLayout.createSequentialGroup()
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationNumberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrationNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumberlbl)
                    .addComponent(serialNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerNamelbl)
                    .addComponent(ownerNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(VehicleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNamelbl)
                    .addComponent(modelNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yearlbl)
                    .addComponent(yearTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114))
        );

        DoctorJPanel.setBackground(new java.awt.Color(255, 255, 255));
        DoctorJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Doctor Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        annualIncomelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        annualIncomelbl.setText("Annual Income");

        nameTx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTx1ActionPerformed(evt);
            }
        });

        doctorIDlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        doctorIDlbl.setText("Doctor ID");

        namelbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        namelbl1.setText("Name");

        educationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        educationlbl.setText("Education");

        workcitylbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        workcitylbl.setText("Work City");

        Specializationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Specializationlbl.setText("Specialization");

        feebl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        feebl.setText("Consultation Fee ");

        feeTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                feeTxKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout DoctorJPanelLayout = new javax.swing.GroupLayout(DoctorJPanel);
        DoctorJPanel.setLayout(DoctorJPanelLayout);
        DoctorJPanelLayout.setHorizontalGroup(
            DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoctorJPanelLayout.createSequentialGroup()
                        .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(educationlbl)
                            .addComponent(namelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameTx1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationTx, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DoctorJPanelLayout.createSequentialGroup()
                        .addComponent(feebl)
                        .addGap(18, 18, 18)
                        .addComponent(feeTx)))
                .addGap(30, 30, 30)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Specializationlbl))
                .addGap(41, 41, 41)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(specializationTx, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorIDTx, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workcitylbl)
                    .addComponent(annualIncomelbl))
                .addGap(66, 66, 66)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(annualIncomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workcityTx, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        DoctorJPanelLayout.setVerticalGroup(
            DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorJPanelLayout.createSequentialGroup()
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoctorJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(doctorIDlbl)
                            .addComponent(doctorIDTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namelbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameTx1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(educationlbl)
                        .addComponent(Specializationlbl)
                        .addComponent(specializationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(educationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feebl)
                    .addComponent(feeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DoctorJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualIncomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annualIncomelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DoctorJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(workcityTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workcitylbl))
                .addGap(12, 12, 12))
        );

        PatientJPanel.setBackground(new java.awt.Color(255, 255, 255));
        PatientJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Patient Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        PatientJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        patientIDlbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        patientIDlbl1.setText("Patient ID");
        PatientJPanel.add(patientIDlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 152, 24));
        PatientJPanel.add(primaryDoctorTx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 238, -1));

        patientIDTx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDTx1ActionPerformed(evt);
            }
        });
        PatientJPanel.add(patientIDTx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 40, 238, -1));

        primaryDoctorlbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        primaryDoctorlbl1.setText("Primary Doctor");
        PatientJPanel.add(primaryDoctorlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 131, -1));

        lastVisitDatelbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastVisitDatelbl1.setText("Last Visit Date");
        PatientJPanel.add(lastVisitDatelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        nextAppointmentDatelbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nextAppointmentDatelbl1.setText("Next Appointment Date");
        PatientJPanel.add(nextAppointmentDatelbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        onMedicationYesRb1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        onMedicationYesRb1.setText("Yes");
        PatientJPanel.add(onMedicationYesRb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, -1, -1));

        allergieslbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        allergieslbl1.setText("Allergies");
        PatientJPanel.add(allergieslbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, -1, -1));

        allergiesNoRb1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        allergiesNoRb1.setText("No");
        PatientJPanel.add(allergiesNoRb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 40, -1, -1));

        onMedicationlbl1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        onMedicationlbl1.setText("On Medication");
        PatientJPanel.add(onMedicationlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        onMedicationNoRb1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        onMedicationNoRb1.setText("No");
        PatientJPanel.add(onMedicationNoRb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 70, -1, -1));

        allergiesYesRb1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        allergiesYesRb1.setText("Yes");
        PatientJPanel.add(allergiesYesRb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 40, -1, -1));
        PatientJPanel.add(LastVisitDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));
        PatientJPanel.add(NewAppointmentDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 80, -1, -1));

        InsuranceJPanel.setBackground(new java.awt.Color(255, 255, 255));
        InsuranceJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Insurance Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        locationTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationTxActionPerformed(evt);
            }
        });

        insuranceTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceTxActionPerformed(evt);
            }
        });

        locationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        locationlbl.setText("Location");

        insuranceID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        insuranceID.setText("Insurance Company ID");

        installationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        installationlbl.setText("Installment");

        statementlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        statementlbl.setText("Benefit Statement");

        deductiblelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        deductiblelbl.setText("Deductible");

        statementTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statementTxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InsuranceJPanelLayout = new javax.swing.GroupLayout(InsuranceJPanel);
        InsuranceJPanel.setLayout(InsuranceJPanelLayout);
        InsuranceJPanelLayout.setHorizontalGroup(
            InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                        .addComponent(insuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(insuranceTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                        .addComponent(deductiblelbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deductibleTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                        .addComponent(locationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(locationTx, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(installationlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(installmentTx, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                        .addComponent(statementlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statementTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        InsuranceJPanelLayout.setVerticalGroup(
            InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(installationlbl)
                    .addComponent(installmentTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                        .addGroup(InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deductibleTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deductiblelbl))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InsuranceJPanelLayout.createSequentialGroup()
                        .addGroup(InsuranceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(statementTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statementlbl))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        DriverJPanel.setBackground(new java.awt.Color(255, 255, 255));
        DriverJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Driver Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        licenselbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        licenselbl.setText("License Number");

        javax.swing.GroupLayout DriverJPanelLayout = new javax.swing.GroupLayout(DriverJPanel);
        DriverJPanel.setLayout(DriverJPanelLayout);
        DriverJPanelLayout.setHorizontalGroup(
            DriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(licenselbl)
                .addGap(18, 18, 18)
                .addComponent(licenseNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DriverJPanelLayout.setVerticalGroup(
            DriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriverJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DriverJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licenselbl)
                    .addComponent(licenseNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addressJPanel.setBackground(new java.awt.Color(255, 255, 255));
        addressJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "Address Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        GPSLocationlbl4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        GPSLocationlbl4.setText("GPS Location");

        GPSLocationTx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPSLocationTx4ActionPerformed(evt);
            }
        });

        citylbl4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        citylbl4.setText("City");

        statelbl4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        statelbl4.setText("State");

        stateTx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTx4ActionPerformed(evt);
            }
        });

        countrylbl4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        countrylbl4.setText("Country");

        javax.swing.GroupLayout addressJPanelLayout = new javax.swing.GroupLayout(addressJPanel);
        addressJPanel.setLayout(addressJPanelLayout);
        addressJPanelLayout.setHorizontalGroup(
            addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPSLocationlbl4)
                    .addComponent(citylbl4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPSLocationTx4, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTx4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countrylbl4)
                    .addComponent(statelbl4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stateTx4, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(countryTx4))
                .addGap(38, 38, 38))
        );
        addressJPanelLayout.setVerticalGroup(
            addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addressJPanelLayout.createSequentialGroup()
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GPSLocationlbl4)
                            .addComponent(GPSLocationTx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statelbl4)))
                    .addComponent(stateTx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addressJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(citylbl4)
                        .addComponent(cityTx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(countryTx4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(countrylbl4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DoctorJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InsuranceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(PatientJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
                        .addComponent(VehicleJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(addressJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DriverJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(personalInformationJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(1143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personalInformationJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DriverJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VehicleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DoctorJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InsuranceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNametxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNametxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNametxActionPerformed

    private void registrationNumberTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationNumberTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationNumberTxActionPerformed

    private void insuranceTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceTxActionPerformed

    private void educationPersonTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_educationPersonTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_educationPersonTxActionPerformed

    private void stateTx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTx4ActionPerformed

    private void GPSLocationTx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPSLocationTx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPSLocationTx4ActionPerformed

    private void patientIDTx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDTx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDTx1ActionPerformed

    private void nameTx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTx1ActionPerformed

    private void hobbyTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hobbyTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hobbyTxActionPerformed

    private void statementTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statementTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statementTxActionPerformed

    private void locationTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationTxActionPerformed

    private void feeTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feeTxKeyPressed
        // TODO add your handling code here:   char c = evt.getKeyChar();
        
    }//GEN-LAST:event_feeTxKeyPressed

    private void displayDoctorInfo() {
        doctorIDTx.setText(doctor.getDoctorId());
        doctorIDTx.setEditable(false);
        educationTx.setText(doctor.getEducation());
        educationTx.setEditable(false);
        String annualIncomeString = String.valueOf(person.getAge());
        annualIncomeTx.setText(annualIncomeString);
        annualIncomeTx.setEditable(false);
        workcityTx.setText(doctor.getWorkCity());
        workcityTx.setEditable(false);
        specializationTx.setText(doctor.getSpecialization());
        specializationTx.setEditable(false);
        nameTx1.setText(doctor.getName());
        nameTx1.setEditable(false);
        String feeString = String.valueOf(doctor.getConsultationFee());
        feeTx.setText(feeString) ; 
        

        System.out.println("Doctor{"
                + "name='" + doctor.getName() + '\''
                + ", workCity='" + doctor.getWorkCity() + '\''
                + ", doctorId='" + doctor.getDoctorId() + '\''
                + ", specialization='" + doctor.getSpecialization() + '\''
                + ", education='" + doctor.getEducation() + '\''
                + ", annualIncome='" + doctor.getAnnualIncome() + '\''
                + ", consultation fee='" + doctor.getConsultationFee() + '\''
                + '}');

    }

    private void displayInsuranceInfo() {

        insuranceTx.setText(insurance.getCompanyId());
        insuranceTx.setEditable(false);
        locationTx.setText(insurance.getWorkLocation());
        locationTx.setEditable(false);
        String deductibleTxString = String.valueOf(insurance.getDeductible());
        deductibleTx.setText(deductibleTxString);
        deductibleTx.setEditable(false);
        String installmentTxString = String.valueOf(insurance.getInstallment());
        installmentTx.setText(installmentTxString);
        installmentTx.setEditable(false);
        statementTx.setText(insurance.getBenefitsStatement());
        statementTx.setEditable(false);

        System.out.println("Insurance Information---->" + "HealthInsuranceCompany{"
                + "companyId='" + insurance.getCompanyId() + '\''
                + ", location='" + insurance.getWorkLocation() + '\''
                + ", installment='" + insurance.getInstallment() + '\''
                + ", deductible='" + insurance.getDeductible() + '\''
                + ", benefitsStatement='" + insurance.getBenefitsStatement() + '\''
                + '}');
    }

    private void displayPatientInfo() {
        patientIDTx1.setText(patient.getPatientId());
        patientIDTx1.setEditable(false);
        primaryDoctorTx1.setText(patient.getPrimaryDoctor());
        primaryDoctorTx1.setEditable(false);
        if (patient.getLastVisitDate() != null) {
            LastVisitDate.setDate(patient.getLastVisitDate());
        }

        if (patient.getNextAppointmentDate() != null) {
            NewAppointmentDate.setDate(patient.getNextAppointmentDate());
        }
        NewAppointmentDate.setEnabled(false);
        LastVisitDate.setEnabled(false);
        
        if (patient.getHasAllergies() != null && patient.getHasAllergies()) {
            allergiesYesRb1.setSelected(true);
        } else {
            allergiesNoRb1.setSelected(true);
        }
        allergiesYesRb1.setEnabled(false);
        allergiesNoRb1.setEnabled(false);
        if (patient.getOnMedication() != null && patient.getOnMedication()) {
            onMedicationYesRb1.setSelected(true);
        } else {
            onMedicationNoRb1.setSelected(true);
        }
        onMedicationYesRb1.setEnabled(false);
        onMedicationNoRb1.setEnabled(false);
        System.out.println("Patient{"
                + "patientId='" + patient.getPrimaryDoctor() + '\''
                + ", primaryDoctor='" + patient.getPrimaryDoctor() + '\''
                + ", lastVisitDate='" + patient.getLastVisitDate() + '\''
                + ", nextAppointmentDate='" + patient.getNextAppointmentDate() + '\''
                + ", allergies='" + patient.getHasAllergies() + '\''
                + ", onMedication='" + patient.getOnMedication() + '\''
                + '}');

    }

    private void displayDriverInfo() {
        
        licenseNumberTx.setText(driver.getLicenseNumber());
        licenseNumberTx.setEditable(false);

        System.out.println("Driver{"
                + ", licenseNumber='" + driver.getLicenseNumber() + '\''
                + '}');

    }

    private void displayVehicleInfo() {
        yearTx.setText(vehicleInfo.getManufacturingYear());
        yearTx.setEditable(false);
        modelNameTx.setText(vehicleInfo.getModelName());
        modelNameTx.setEditable(false);
        ownerNameTx.setText(vehicleInfo.getOwnerName());
        ownerNameTx.setEditable(false);
        serialNumberTx.setText(vehicleInfo.getSerialnNumber());
        serialNumberTx.setEditable(false);
        registrationNumberTx.setText(vehicleInfo.getRegistrationNumber());
        registrationNumberTx.setEditable(false);

        System.out.println("VehicleRegistration{"
                + "registrationNumber='" + vehicleInfo.getRegistrationNumber() + '\''
                + "serialNumber='" + vehicleInfo.getSerialnNumber() + '\''
                + ", modelName='" + vehicleInfo.getModelName() + '\''
                + ", manufacturingYear='" + vehicleInfo.getManufacturingYear() + '\''
                + ", ownerName='" + vehicleInfo.getOwnerName() + '\''
                + '}');
    }

    private void displayPersonInfo() {

        firstNametx.setText(person.getFirstName());
        firstNametx.setEditable(false);
        lastNameTx.setText(person.getLastName());
        lastNameTx.setEditable(false);
        hobbyTx.setText(person.getHobby());
        String ageString = String.valueOf(person.getAge());
        ageTx.setText(ageString);
        
        ageTx.setEditable(false);
        passportTx.setText(person.getPassportNumber());
        passportTx.setEditable(false);
        educationPersonTx.setText(person.getEducation());
        educationPersonTx.setEditable(false);
        String SSNString = String.valueOf(person.getSSN());
        SSNTx.setText(SSNString);
        SSNTx.setEditable(false);
        bloodTypeTx.setText(person.getBooldType());
        bloodTypeTx.setEditable(false);
        occupationTx.setText(person.getOccupation());
        occupationTx.setEditable(false);
        //pictureTx.setText(person.getPicture());
        //pictureTx.setEditable(false);
        String phoneNumberString = String.valueOf(person.getPhoneNumber());
        phoneNumberTx.setText(phoneNumberString);
        phoneNumberTx.setEditable(false);
        cityTx4.setText(address.getCity());
        cityTx4.setEditable(false);
        stateTx4.setText(address.getState());
        stateTx4.setEditable(false);
        countryTx4.setText(address.getCountry());
        countryTx4.setEditable(false);
        GPSLocationTx4.setText(address.getGPSLocation());
        GPSLocationTx4.setEditable(false);

        System.out.println("Person{" + "firstName=" + person.getFirstName() + ", lastName=" + person.getLastName() + ", age=" + person.getAge() + ", education=" + person.getEducation() + ", Blood Type=" + person.getBooldType()+ ", phoneNumber=" + person.getPhoneNumber() + ", Passport Number=" + person.getPassportNumber()+ ", SSN=" + person.getSSN() + ", Hobby=" + person.getHobby()+ ", occupation=" + person.getOccupation() + '}');

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorJPanel;
    private javax.swing.JPanel DriverJPanel;
    private javax.swing.JTextField GPSLocationTx4;
    private javax.swing.JLabel GPSLocationlbl4;
    private javax.swing.JPanel InsuranceJPanel;
    private com.toedter.calendar.JDateChooser LastVisitDate;
    private com.toedter.calendar.JDateChooser NewAppointmentDate;
    private javax.swing.JPanel PatientJPanel;
    private javax.swing.JTextField SSNTx;
    private javax.swing.JLabel SSNlbl;
    private javax.swing.JLabel Specializationlbl;
    private javax.swing.JPanel VehicleJPanel;
    private javax.swing.JPanel addressJPanel;
    private javax.swing.JTextField ageTx;
    private javax.swing.JLabel agelbl;
    private javax.swing.JRadioButton allergiesNoRb1;
    private javax.swing.JRadioButton allergiesYesRb1;
    private javax.swing.JLabel allergieslbl1;
    private javax.swing.JTextField annualIncomeTx;
    private javax.swing.JLabel annualIncomelbl;
    private javax.swing.JTextField bloodTypeTx;
    private javax.swing.JLabel bloodTypelbl;
    private javax.swing.JTextField cityTx4;
    private javax.swing.JLabel citylbl4;
    private javax.swing.JTextField countryTx4;
    private javax.swing.JLabel countrylbl4;
    private javax.swing.JTextField deductibleTx;
    private javax.swing.JLabel deductiblelbl;
    private javax.swing.JTextField doctorIDTx;
    private javax.swing.JLabel doctorIDlbl;
    private javax.swing.JTextField educationPersonTx;
    private javax.swing.JLabel educationPersonlbl;
    private javax.swing.JTextField educationTx;
    private javax.swing.JLabel educationlbl;
    private javax.swing.JTextField feeTx;
    private javax.swing.JLabel feebl;
    private javax.swing.JLabel firstNamelbl;
    private javax.swing.JTextField firstNametx;
    private javax.swing.JTextField hobbyTx;
    private javax.swing.JLabel hobbylbl;
    private javax.swing.JLabel installationlbl;
    private javax.swing.JTextField installmentTx;
    private javax.swing.JLabel insuranceID;
    private javax.swing.JTextField insuranceTx;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTx;
    private javax.swing.JLabel lastNamelbl;
    private javax.swing.JLabel lastVisitDatelbl1;
    private javax.swing.JTextField licenseNumberTx;
    private javax.swing.JLabel licenselbl;
    private javax.swing.JTextField locationTx;
    private javax.swing.JLabel locationlbl;
    private javax.swing.JTextField modelNameTx;
    private javax.swing.JLabel modelNamelbl;
    private javax.swing.JTextField nameTx1;
    private javax.swing.JLabel namelbl1;
    private javax.swing.JLabel nextAppointmentDatelbl1;
    private javax.swing.JTextField occupationTx;
    private javax.swing.JLabel occupationlbl;
    private javax.swing.JRadioButton onMedicationNoRb1;
    private javax.swing.JRadioButton onMedicationYesRb1;
    private javax.swing.JLabel onMedicationlbl1;
    private javax.swing.JTextField ownerNameTx;
    private javax.swing.JLabel ownerNamelbl;
    private javax.swing.JTextField passportTx;
    private javax.swing.JLabel passportlbl;
    private javax.swing.JTextField patientIDTx1;
    private javax.swing.JLabel patientIDlbl1;
    private javax.swing.JPanel personalInformationJPanel;
    private javax.swing.JTextField phoneNumberTx;
    private javax.swing.JLabel phoneNumberlbl;
    private javax.swing.JTextField primaryDoctorTx1;
    private javax.swing.JLabel primaryDoctorlbl1;
    private javax.swing.JTextField registrationNumberTx;
    private javax.swing.JLabel registrationNumberlbl;
    private javax.swing.JTextField serialNumberTx;
    private javax.swing.JLabel serialNumberlbl;
    private javax.swing.JTextField specializationTx;
    private javax.swing.JTextField stateTx4;
    private javax.swing.JLabel statelbl4;
    private javax.swing.JTextField statementTx;
    private javax.swing.JLabel statementlbl;
    private javax.swing.JTextField workcityTx;
    private javax.swing.JLabel workcitylbl;
    private javax.swing.JTextField yearTx;
    private javax.swing.JLabel yearlbl;
    // End of variables declaration//GEN-END:variables
}
