/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.*;
import javax.swing.JOptionPane;
/**
 *
 * @author shrey
 */
public class DoctorJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorJPanel
     */
    Doctor doctor;
    public DoctorJPanel(Doctor doctor) {
        initComponents();
        this.doctor= doctor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        specializationTx = new javax.swing.JTextField();
        doctorSaveButton = new javax.swing.JButton();
        namelbl = new javax.swing.JLabel();
        workcitylbl = new javax.swing.JLabel();
        educationTx = new javax.swing.JTextField();
        doctorIDTx = new javax.swing.JTextField();
        nameTx = new javax.swing.JTextField();
        doctorIDlbl = new javax.swing.JLabel();
        educationlbl = new javax.swing.JLabel();
        Specializationlbl = new javax.swing.JLabel();
        annualIncomelbl = new javax.swing.JLabel();
        workcityTx = new javax.swing.JTextField();
        annualIncomeTx = new javax.swing.JTextField();
        feebl = new javax.swing.JLabel();
        feeTx = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Doctor Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 18))); // NOI18N

        doctorSaveButton.setBackground(new java.awt.Color(0, 0, 102));
        doctorSaveButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        doctorSaveButton.setForeground(new java.awt.Color(255, 255, 255));
        doctorSaveButton.setText("Save");
        doctorSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doctorSaveButtonActionPerformed(evt);
            }
        });

        namelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        namelbl.setText("Name*");

        workcitylbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        workcitylbl.setText("Work City");

        nameTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxActionPerformed(evt);
            }
        });

        doctorIDlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        doctorIDlbl.setText("Doctor ID*");

        educationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        educationlbl.setText("Education");

        Specializationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Specializationlbl.setText("Specialization");

        annualIncomelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        annualIncomelbl.setText("Annual Income");

        annualIncomeTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                annualIncomeTxKeyPressed(evt);
            }
        });

        feebl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        feebl.setText("Consultation Fee ");

        feeTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeTxActionPerformed(evt);
            }
        });
        feeTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                feeTxKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(doctorIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(educationlbl)
                            .addComponent(Specializationlbl)
                            .addComponent(workcitylbl)
                            .addComponent(annualIncomelbl)
                            .addComponent(feebl))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameTx, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(doctorIDTx)
                            .addComponent(educationTx)
                            .addComponent(specializationTx)
                            .addComponent(workcityTx)
                            .addComponent(annualIncomeTx, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(feeTx)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(doctorSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorIDTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doctorIDlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(educationlbl)
                    .addComponent(educationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Specializationlbl)
                    .addComponent(specializationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workcitylbl)
                    .addComponent(workcityTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualIncomelbl)
                    .addComponent(annualIncomeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feebl)
                    .addComponent(feeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(doctorSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void doctorSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doctorSaveButtonActionPerformed
        // TODO add your handling code here:

        try{
        if( !annualIncomeTx.getText().isBlank() || !annualIncomeTx.getText().isEmpty()){
        if (annualIncomeTx.getText().matches("\\d+")) {
        int  annualIncome = Integer.parseInt(annualIncomeTx.getText());
        doctor.setAnnualIncome(annualIncome);
        }
        }
        if( !feeTx.getText().isBlank() || !feeTx.getText().isEmpty()){
        if (annualIncomeTx.getText().matches("\\d+")) {
        int  annualIncome = Integer.parseInt(feeTx.getText());
        doctor.setAnnualIncome(annualIncome);
        }
        }
        }catch(Exception e){
            
        }
        doctor.setDoctorId(doctorIDTx.getText());
        doctor.setEducation(educationTx.getText());
        doctor.setName(nameTx.getText());
        doctor.setSpecialization(specializationTx.getText());
        doctor.setWorkCity(workcityTx.getText());
       
        if (doctorIDTx.getText().isEmpty() || nameTx.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please entry the required fields.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Doctor Information Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_doctorSaveButtonActionPerformed

    private void nameTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxActionPerformed

    private void annualIncomeTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_annualIncomeTxKeyPressed
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            annualIncomeTx.setEditable(false);
             JOptionPane.showMessageDialog(null, "Please entry numbers only.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            annualIncomeTx.setEditable(true);
        }
    }//GEN-LAST:event_annualIncomeTxKeyPressed

    private void feeTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_feeTxKeyPressed
        // TODO add your handling code here:   char c = evt.getKeyChar();
         char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            feeTx.setEditable(false);
             JOptionPane.showMessageDialog(null, "Please entry numbers only.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            feeTx.setEditable(true);
        }
        
    }//GEN-LAST:event_feeTxKeyPressed

    private void feeTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeTxActionPerformed
      
    }//GEN-LAST:event_feeTxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Specializationlbl;
    private javax.swing.JTextField annualIncomeTx;
    private javax.swing.JLabel annualIncomelbl;
    private javax.swing.JTextField doctorIDTx;
    private javax.swing.JLabel doctorIDlbl;
    private javax.swing.JButton doctorSaveButton;
    private javax.swing.JTextField educationTx;
    private javax.swing.JLabel educationlbl;
    private javax.swing.JTextField feeTx;
    private javax.swing.JLabel feebl;
    private javax.swing.JTextField nameTx;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField specializationTx;
    private javax.swing.JTextField workcityTx;
    private javax.swing.JLabel workcitylbl;
    // End of variables declaration//GEN-END:variables
}
