/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author shrey
 */
public class InsuranceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceJPanel
     */
    Insurance insurance;
    public InsuranceJPanel(Insurance insurance) {
        initComponents();
        this.insurance =  insurance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statementTx = new javax.swing.JTextField();
        installmentTx = new javax.swing.JTextField();
        locationTx = new javax.swing.JTextField();
        deductibleTx = new javax.swing.JTextField();
        insuranceTx = new javax.swing.JTextField();
        locationlbl = new javax.swing.JLabel();
        insuranceID = new javax.swing.JLabel();
        installationlbl = new javax.swing.JLabel();
        statementlbl = new javax.swing.JLabel();
        deductiblelbl = new javax.swing.JLabel();
        insuranceSavebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Insurance Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 18))); // NOI18N

        installmentTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                installmentTxKeyPressed(evt);
            }
        });

        deductibleTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                deductibleTxKeyPressed(evt);
            }
        });

        insuranceTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceTxActionPerformed(evt);
            }
        });

        locationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        locationlbl.setText("Location");

        insuranceID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        insuranceID.setText("Insurance Company ID *");

        installationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        installationlbl.setText("Installation *");

        statementlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        statementlbl.setText("Benefit Statement");

        deductiblelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        deductiblelbl.setText("Deductible");

        insuranceSavebtn.setBackground(new java.awt.Color(0, 0, 102));
        insuranceSavebtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        insuranceSavebtn.setForeground(new java.awt.Color(255, 255, 255));
        insuranceSavebtn.setText("Save");
        insuranceSavebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceSavebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(locationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(installationlbl)
                            .addComponent(deductiblelbl)
                            .addComponent(statementlbl)
                            .addComponent(insuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(insuranceTx)
                            .addComponent(locationTx)
                            .addComponent(installmentTx)
                            .addComponent(deductibleTx)
                            .addComponent(statementTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(insuranceSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insuranceID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insuranceTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(locationlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(installationlbl)
                    .addComponent(installmentTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deductiblelbl)
                    .addComponent(deductibleTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statementlbl)
                    .addComponent(statementTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(insuranceSavebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void insuranceTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceTxActionPerformed

    private void insuranceSavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceSavebtnActionPerformed
        // TODO add your handling code here:
        
        insurance.setBenefitsStatement(statementTx.getText());
        insurance.setCompanyId(insuranceTx.getText());
        
        try{
        if( !deductibleTx.getText().isBlank() || !deductibleTx.getText().isEmpty()){
        if (deductibleTx.getText().matches("-?\\d+(\\.\\d+)?")) {
        double deductible = Double.parseDouble(deductibleTx.getText());
        insurance.setDeductible(deductible);
        }
        }
        
        if( !installmentTx.getText().isBlank() || !installmentTx.getText().isEmpty()){
        if (installmentTx.getText().matches("-?\\d+(\\.\\d+)?")) {
        double installmentInt = Double.parseDouble(installmentTx.getText());
        insurance.setInstallment(installmentInt);
        }
        }
        }catch(Exception e){
            
        }
        insurance.setWorkLocation(locationTx.getText());
        

        if (installmentTx.getText().isEmpty() || insuranceTx.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please entry the required fields.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Insurance Information Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_insuranceSavebtnActionPerformed

    private void installmentTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_installmentTxKeyPressed
        // TODO add your handling code here:
          char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            installmentTx.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter Number only.", "Warning", JOptionPane.ERROR_MESSAGE);

        } else {
            installmentTx.setEditable(true);
        }
    }//GEN-LAST:event_installmentTxKeyPressed

    private void deductibleTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deductibleTxKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            deductibleTx.setEditable(false);
             JOptionPane.showMessageDialog(null, "Please enter Number only.", "Warning", JOptionPane.ERROR_MESSAGE);
//int ERROR_MESSAGE = JOptionPane.ERROR_MESSAGE;
        } else {
            deductibleTx.setEditable(true);
        }
    }//GEN-LAST:event_deductibleTxKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField deductibleTx;
    private javax.swing.JLabel deductiblelbl;
    private javax.swing.JLabel installationlbl;
    private javax.swing.JTextField installmentTx;
    private javax.swing.JLabel insuranceID;
    private javax.swing.JButton insuranceSavebtn;
    private javax.swing.JTextField insuranceTx;
    private javax.swing.JTextField locationTx;
    private javax.swing.JLabel locationlbl;
    private javax.swing.JTextField statementTx;
    private javax.swing.JLabel statementlbl;
    // End of variables declaration//GEN-END:variables
}
