/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import model.*;
import javax.swing.JFrame;

/**
 *
 * @author shrey
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    Person person;
    Driver driver;
    VehicleRegistration vehicleInfo;
    Patient patient;
    Doctor doctor;
    Insurance insurance;
    Address address;
    
    public MainJFrame() {
        initComponents();
        
        person = new Person();
        driver = new Driver();
        vehicleInfo = new VehicleRegistration();
        patient = new Patient();
        doctor = new Doctor();
        insurance = new Insurance();
        address = new Address();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SplitPane = new javax.swing.JSplitPane();
        ControlPanel = new javax.swing.JPanel();
        Person = new javax.swing.JButton();
        Driver = new javax.swing.JButton();
        VehicleRegistration = new javax.swing.JButton();
        Patient = new javax.swing.JButton();
        Doctor = new javax.swing.JButton();
        DisplayPatientReport = new javax.swing.JButton();
        Insurance = new javax.swing.JButton();
        WorkPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AED Lab Assignment ");

        ControlPanel.setBackground(new java.awt.Color(255, 255, 255));
        ControlPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Person.setBackground(new java.awt.Color(0, 0, 102));
        Person.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Person.setForeground(new java.awt.Color(255, 255, 255));
        Person.setText("Person");
        Person.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonActionPerformed(evt);
            }
        });

        Driver.setBackground(new java.awt.Color(0, 0, 102));
        Driver.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Driver.setForeground(new java.awt.Color(255, 255, 255));
        Driver.setText("Driver");
        Driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverActionPerformed(evt);
            }
        });

        VehicleRegistration.setBackground(new java.awt.Color(0, 0, 102));
        VehicleRegistration.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        VehicleRegistration.setForeground(new java.awt.Color(255, 255, 255));
        VehicleRegistration.setText("Vehicle Registration ");
        VehicleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehicleRegistrationActionPerformed(evt);
            }
        });

        Patient.setBackground(new java.awt.Color(0, 0, 102));
        Patient.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Patient.setForeground(new java.awt.Color(255, 255, 255));
        Patient.setText("Patient ");
        Patient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientActionPerformed(evt);
            }
        });

        Doctor.setBackground(new java.awt.Color(0, 0, 102));
        Doctor.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Doctor.setForeground(new java.awt.Color(255, 255, 255));
        Doctor.setText("Doctor");
        Doctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoctorActionPerformed(evt);
            }
        });

        DisplayPatientReport.setBackground(new java.awt.Color(0, 0, 102));
        DisplayPatientReport.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        DisplayPatientReport.setForeground(new java.awt.Color(255, 255, 255));
        DisplayPatientReport.setText("Display Patient Report ");
        DisplayPatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayPatientReportActionPerformed(evt);
            }
        });

        Insurance.setBackground(new java.awt.Color(0, 0, 102));
        Insurance.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Insurance.setForeground(new java.awt.Color(255, 255, 255));
        Insurance.setText("Insurance");
        Insurance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsuranceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPanelLayout = new javax.swing.GroupLayout(ControlPanel);
        ControlPanel.setLayout(ControlPanelLayout);
        ControlPanelLayout.setHorizontalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Insurance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Doctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Patient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VehicleRegistration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Driver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Person, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ControlPanelLayout.createSequentialGroup()
                        .addComponent(DisplayPatientReport)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ControlPanelLayout.setVerticalGroup(
            ControlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Person)
                .addGap(18, 18, 18)
                .addComponent(Driver)
                .addGap(18, 18, 18)
                .addComponent(VehicleRegistration)
                .addGap(18, 18, 18)
                .addComponent(Patient)
                .addGap(18, 18, 18)
                .addComponent(Doctor)
                .addGap(12, 12, 12)
                .addComponent(Insurance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DisplayPatientReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(ControlPanel);

        WorkPanel.setBackground(new java.awt.Color(255, 255, 255));
        WorkPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout WorkPanelLayout = new javax.swing.GroupLayout(WorkPanel);
        WorkPanel.setLayout(WorkPanelLayout);
        WorkPanelLayout.setHorizontalGroup(
            WorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        WorkPanelLayout.setVerticalGroup(
            WorkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(WorkPanel);

        jScrollPane1.setViewportView(SplitPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonActionPerformed
        // TODO add your handling code here:
        PersonJPanel personPanel = new PersonJPanel(person,address);
        
        SplitPane.setRightComponent(personPanel);
       
        
    }//GEN-LAST:event_PersonActionPerformed

    private void DisplayPatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayPatientReportActionPerformed
        // TODO add your handling code here:
        DisplayReportJPanel reportPanel = new DisplayReportJPanel(person,address,driver,vehicleInfo,patient,doctor,insurance);
        SplitPane.setRightComponent(reportPanel);
    }//GEN-LAST:event_DisplayPatientReportActionPerformed

    private void DriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverActionPerformed
        // TODO add your handling code here:
        DriverJPanel driverPanel = new DriverJPanel(driver);
        SplitPane.setRightComponent(driverPanel);
    }//GEN-LAST:event_DriverActionPerformed

    private void VehicleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehicleRegistrationActionPerformed
        // TODO add your handling code here:
        VehicleRegistrationJPanel vehiclePanel = new VehicleRegistrationJPanel(vehicleInfo);
        SplitPane.setRightComponent( vehiclePanel);
    }//GEN-LAST:event_VehicleRegistrationActionPerformed

    private void PatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientActionPerformed
        // TODO add your handling code here:
        PatientJPanel patientPanel = new PatientJPanel(patient);
        SplitPane.setRightComponent( patientPanel);
    }//GEN-LAST:event_PatientActionPerformed

    private void DoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoctorActionPerformed
        // TODO add your handling code here:
        DoctorJPanel doctorPanel = new DoctorJPanel(doctor);
        SplitPane.setRightComponent( doctorPanel);
    }//GEN-LAST:event_DoctorActionPerformed

    private void InsuranceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsuranceActionPerformed
        // TODO add your handling code here:
        InsuranceJPanel insurancePanel = new InsuranceJPanel(insurance);
        SplitPane.setRightComponent( insurancePanel);
    }//GEN-LAST:event_InsuranceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPanel;
    private javax.swing.JButton DisplayPatientReport;
    private javax.swing.JButton Doctor;
    private javax.swing.JButton Driver;
    private javax.swing.JButton Insurance;
    private javax.swing.JButton Patient;
    private javax.swing.JButton Person;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton VehicleRegistration;
    private javax.swing.JPanel WorkPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
