/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author shrey
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    Patient patient;
    public PatientJPanel(Patient patient) {
        initComponents();
        this.patient = patient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        SaveButton = new javax.swing.JButton();
        patientIDlbl = new javax.swing.JLabel();
        primaryDoctorTx = new javax.swing.JTextField();
        patientIDTx = new javax.swing.JTextField();
        primaryDoctorlbl = new javax.swing.JLabel();
        lastVisitDatelbl = new javax.swing.JLabel();
        nextAppointmentDatelbl = new javax.swing.JLabel();
        ownerNamelbl = new javax.swing.JLabel();
        onMedicationYesRb = new javax.swing.JRadioButton();
        allergieslbl = new javax.swing.JLabel();
        allergiesNoRb = new javax.swing.JRadioButton();
        onMedicationlbl = new javax.swing.JLabel();
        onMedicationNoRb = new javax.swing.JRadioButton();
        allergiesYesRb = new javax.swing.JRadioButton();
        lastVisitDate = new com.toedter.calendar.JDateChooser();
        NewAppointmentDate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Patient Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 18))); // NOI18N

        SaveButton.setBackground(new java.awt.Color(0, 0, 102));
        SaveButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        patientIDlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        patientIDlbl.setText("Patient ID *");

        patientIDTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDTxActionPerformed(evt);
            }
        });

        primaryDoctorlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        primaryDoctorlbl.setText("Primary Doctor");

        lastVisitDatelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastVisitDatelbl.setText("Last Visit Date");

        nextAppointmentDatelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        nextAppointmentDatelbl.setText("Next Appointment Date");

        buttonGroup2.add(onMedicationYesRb);
        onMedicationYesRb.setText("Yes");

        allergieslbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        allergieslbl.setText("Allergies");

        buttonGroup1.add(allergiesNoRb);
        allergiesNoRb.setText("No");

        onMedicationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        onMedicationlbl.setText("On Medication");

        buttonGroup2.add(onMedicationNoRb);
        onMedicationNoRb.setText("No");

        buttonGroup1.add(allergiesYesRb);
        allergiesYesRb.setText("Yes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(primaryDoctorlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(patientIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastVisitDatelbl)
                                    .addComponent(nextAppointmentDatelbl)
                                    .addComponent(onMedicationlbl)
                                    .addComponent(allergieslbl)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(ownerNamelbl)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(primaryDoctorTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientIDTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NewAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(allergiesNoRb)
                                    .addComponent(onMedicationNoRb)))
                            .addComponent(allergiesYesRb)
                            .addComponent(onMedicationYesRb))))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientIDlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(patientIDTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaryDoctorlbl)
                    .addComponent(primaryDoctorTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastVisitDatelbl)
                    .addComponent(lastVisitDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextAppointmentDatelbl)
                    .addComponent(NewAppointmentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allergieslbl)
                    .addComponent(allergiesYesRb)
                    .addComponent(allergiesNoRb))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onMedicationlbl)
                    .addComponent(onMedicationYesRb)
                    .addComponent(onMedicationNoRb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerNamelbl)
                .addGap(56, 56, 56)
                .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
       
        patient.setPatientId(patientIDTx.getText());
        patient.setPrimaryDoctor(primaryDoctorTx.getText());
        patient.setLastVisitDate(lastVisitDate.getDate());
        patient.setNextAppointmentDate(NewAppointmentDate.getDate());
        
        if(allergiesYesRb.isSelected())
                patient.setHasAllergies(true);
        else  
                patient.setHasAllergies(false);
        
        if(onMedicationYesRb.isSelected())
                patient.setOnMedication(true);
        else  
                patient.setOnMedication(false);
        
        
        System.out.println("allergies No "+allergiesNoRb.isSelected()+"allergies Yes"+allergiesYesRb.isSelected());
      
        if (patientIDTx.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please entry the required fields.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Patient Information Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void patientIDTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDTxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser NewAppointmentDate;
    private javax.swing.JButton SaveButton;
    private javax.swing.JRadioButton allergiesNoRb;
    private javax.swing.JRadioButton allergiesYesRb;
    private javax.swing.JLabel allergieslbl;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser lastVisitDate;
    private javax.swing.JLabel lastVisitDatelbl;
    private javax.swing.JLabel nextAppointmentDatelbl;
    private javax.swing.JRadioButton onMedicationNoRb;
    private javax.swing.JRadioButton onMedicationYesRb;
    private javax.swing.JLabel onMedicationlbl;
    private javax.swing.JLabel ownerNamelbl;
    private javax.swing.JTextField patientIDTx;
    private javax.swing.JLabel patientIDlbl;
    private javax.swing.JTextField primaryDoctorTx;
    private javax.swing.JLabel primaryDoctorlbl;
    // End of variables declaration//GEN-END:variables
}
