/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import model.Person;
import model.Address;

/**
 *
 * @author shrey
 */
public class PersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PersonJPanel
     */
    Person person;
    Address address;

    public PersonJPanel(Person person, Address address) {

        initComponents();
        this.person = person;
        this.address = address;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNamelbl = new javax.swing.JLabel();
        firstNametx = new javax.swing.JTextField();
        Savebtn = new javax.swing.JButton();
        lastNamelbl = new javax.swing.JLabel();
        lastNameTx = new javax.swing.JTextField();
        agelbl = new javax.swing.JLabel();
        ageTx = new javax.swing.JTextField();
        educationPersonlbl = new javax.swing.JLabel();
        educationPersonTx = new javax.swing.JTextField();
        booldTypelbl = new javax.swing.JLabel();
        bloodTypeTx = new javax.swing.JTextField();
        phoneNumberlbl = new javax.swing.JLabel();
        phoneNumberTx = new javax.swing.JTextField();
        SSNlbl = new javax.swing.JLabel();
        SSNTx = new javax.swing.JTextField();
        Hobby = new javax.swing.JLabel();
        hobbyTx = new javax.swing.JTextField();
        passportlbl = new javax.swing.JLabel();
        passportTx = new javax.swing.JTextField();
        occupationTx = new javax.swing.JTextField();
        occupationlbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        GPSLocationlbl = new javax.swing.JLabel();
        citylbl = new javax.swing.JLabel();
        GPSLocationTx = new javax.swing.JTextField();
        cityTx = new javax.swing.JTextField();
        statelbl = new javax.swing.JLabel();
        countrylbl = new javax.swing.JLabel();
        stateTx = new javax.swing.JTextField();
        countryTx = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Personal Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        setPreferredSize(new java.awt.Dimension(558, 541));

        firstNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        firstNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        firstNamelbl.setText("First Name *");

        firstNametx.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        firstNametx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNametxActionPerformed(evt);
            }
        });

        Savebtn.setBackground(new java.awt.Color(0, 0, 102));
        Savebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(255, 255, 255));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        lastNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastNamelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lastNamelbl.setText("Last Name *");

        lastNameTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        agelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        agelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        agelbl.setText("Age");

        ageTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ageTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ageTxKeyPressed(evt);
            }
        });

        educationPersonlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        educationPersonlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        educationPersonlbl.setText("Education");

        educationPersonTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        booldTypelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        booldTypelbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        booldTypelbl.setText("Blood Type");

        bloodTypeTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        phoneNumberlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        phoneNumberlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        phoneNumberlbl.setText("Phone Number *");

        phoneNumberTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneNumberTxKeyPressed(evt);
            }
        });

        SSNlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        SSNlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        SSNlbl.setText("Social Security Number *");

        SSNTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        SSNTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SSNTxKeyPressed(evt);
            }
        });

        Hobby.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        Hobby.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Hobby.setText("Hobby");

        hobbyTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        passportlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        passportlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passportlbl.setText("Passport Number");

        passportTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        occupationTx.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        occupationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        occupationlbl.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        occupationlbl.setText("Occupation");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Address Information ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 14))); // NOI18N

        GPSLocationlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        GPSLocationlbl.setText("GPS Location");

        citylbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        citylbl.setText("City");

        GPSLocationTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPSLocationTxActionPerformed(evt);
            }
        });

        statelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        statelbl.setText("State");

        countrylbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        countrylbl.setText("Country");

        stateTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPSLocationlbl)
                    .addComponent(citylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GPSLocationTx, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityTx, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(countrylbl)
                    .addComponent(statelbl))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stateTx, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(countryTx))
                .addGap(0, 124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GPSLocationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statelbl)
                    .addComponent(GPSLocationlbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citylbl)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(countrylbl)
                        .addComponent(cityTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stateTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countryTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNamelbl)
                            .addComponent(agelbl)
                            .addComponent(educationPersonlbl)
                            .addComponent(booldTypelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(educationPersonTx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ageTx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameTx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNametx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bloodTypeTx, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SSNlbl)
                            .addComponent(phoneNumberlbl)
                            .addComponent(Hobby)
                            .addComponent(passportlbl)
                            .addComponent(occupationlbl))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(phoneNumberTx, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                            .addComponent(SSNTx)
                            .addComponent(hobbyTx)
                            .addComponent(passportTx)
                            .addComponent(occupationTx)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(Savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(firstNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(firstNametx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(phoneNumberlbl, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNamelbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(SSNlbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agelbl)
                            .addComponent(ageTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hobby))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(educationPersonlbl)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(educationPersonTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passportlbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(occupationlbl)
                            .addComponent(booldTypelbl)
                            .addComponent(bloodTypeTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(phoneNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SSNTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hobbyTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passportTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(occupationTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void firstNametxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNametxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNametxActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed

        person.setFirstName(firstNametx.getText());
        person.setLastName(lastNameTx.getText());
        try{
        if( !ageTx.getText().isBlank() || !ageTx.getText().isEmpty()){
        if (ageTx.getText().matches("\\d+")) {
        int personAge = Integer.parseInt(ageTx.getText());
        person.setAge(personAge);
        }
        }
        //person.setAge(ageTx.getText());
        person.setPassportNumber(passportTx.getText());
        if( !phoneNumberTx.getText().isBlank() || !phoneNumberTx.getText().isEmpty()){
        if (phoneNumberTx.getText().matches("\\d+")) {
        int personPhoneNumber = Integer.parseInt(phoneNumberTx.getText());
        person.setPhoneNumber(personPhoneNumber);
        }
        }
        }catch(Exception e)
        {
            
        }
        //person.setPhoneNumber(phoneNumberTx.getText());
        person.setSSN(SSNTx.getText());
        person.setOccupation(occupationTx.getText());
        person.setBooldType(bloodTypeTx.getText());
        person.setHobby(hobbyTx.getText());
        person.setEducation(educationPersonTx.getText());
        address.setCity(cityTx.getText());
        address.setCountry(countryTx.getText());
        address.setGPSLocation(GPSLocationTx.getText());
        address.setState(stateTx.getText());
    
        if (firstNametx.getText().isEmpty() || lastNameTx.getText().isEmpty() || SSNTx.getText().isEmpty() || phoneNumberTx.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please entry all the required fields.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else if (phoneNumberTx.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Phone number should be of 10 digit.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Person Information Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_SavebtnActionPerformed

    private void stateTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTxActionPerformed

    private void GPSLocationTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPSLocationTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPSLocationTxActionPerformed

    private void phoneNumberTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneNumberTxKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            phoneNumberTx.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter Number only.", "Warning", JOptionPane.ERROR_MESSAGE);
               //int ERROR_MESSAGE = JOptionPane.ERROR_MESSAGE;
        } else {
            phoneNumberTx.setEditable(true);
        }
    }//GEN-LAST:event_phoneNumberTxKeyPressed

    private void ageTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTxKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            ageTx.setEditable(false);
            JOptionPane.showMessageDialog(null, "Please enter Number only.", "Warning", JOptionPane.ERROR_MESSAGE);
            } else {
            ageTx.setEditable(true);
        }
    }//GEN-LAST:event_ageTxKeyPressed

    private void SSNTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SSNTxKeyPressed

        // TODO add your handling code here:
        
    }//GEN-LAST:event_SSNTxKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField GPSLocationTx;
    private javax.swing.JLabel GPSLocationlbl;
    private javax.swing.JLabel Hobby;
    private javax.swing.JTextField SSNTx;
    private javax.swing.JLabel SSNlbl;
    private javax.swing.JButton Savebtn;
    private javax.swing.JTextField ageTx;
    private javax.swing.JLabel agelbl;
    private javax.swing.JTextField bloodTypeTx;
    private javax.swing.JLabel booldTypelbl;
    private javax.swing.JTextField cityTx;
    private javax.swing.JLabel citylbl;
    private javax.swing.JTextField countryTx;
    private javax.swing.JLabel countrylbl;
    private javax.swing.JTextField educationPersonTx;
    private javax.swing.JLabel educationPersonlbl;
    private javax.swing.JLabel firstNamelbl;
    private javax.swing.JTextField firstNametx;
    private javax.swing.JTextField hobbyTx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameTx;
    private javax.swing.JLabel lastNamelbl;
    private javax.swing.JTextField occupationTx;
    private javax.swing.JLabel occupationlbl;
    private javax.swing.JTextField passportTx;
    private javax.swing.JLabel passportlbl;
    private javax.swing.JTextField phoneNumberTx;
    private javax.swing.JLabel phoneNumberlbl;
    private javax.swing.JTextField stateTx;
    private javax.swing.JLabel statelbl;
    // End of variables declaration//GEN-END:variables
}
