/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author shrey
 */
public class VehicleRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form VehicleRegistrationJPanel
     */
    VehicleRegistration vehicleInfo;
    public VehicleRegistrationJPanel(VehicleRegistration vehicleInfo) {
        initComponents();
        this.vehicleInfo = vehicleInfo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SaveButton = new javax.swing.JButton();
        registrationNumberlbl = new javax.swing.JLabel();
        modelNameTx = new javax.swing.JTextField();
        serialNumberTx = new javax.swing.JTextField();
        registrationNumberTx = new javax.swing.JTextField();
        serialNumberlbl = new javax.swing.JLabel();
        modelNamelbl = new javax.swing.JLabel();
        yearlbl = new javax.swing.JLabel();
        yearTx = new javax.swing.JTextField();
        ownerNamelbl = new javax.swing.JLabel();
        ownerNameTx = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vehicle Registration Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semibold", 1, 18))); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));

        SaveButton.setBackground(new java.awt.Color(0, 0, 102));
        SaveButton.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        SaveButton.setForeground(new java.awt.Color(255, 255, 255));
        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        registrationNumberlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        registrationNumberlbl.setText("Registration Number *");

        registrationNumberTx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationNumberTxActionPerformed(evt);
            }
        });

        serialNumberlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        serialNumberlbl.setText("Serial Number ");

        modelNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        modelNamelbl.setText("Model Name");

        yearlbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        yearlbl.setText("Year");

        yearTx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                yearTxKeyPressed(evt);
            }
        });

        ownerNamelbl.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        ownerNamelbl.setText("Owner Name *");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serialNumberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(registrationNumberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modelNamelbl)
                            .addComponent(ownerNamelbl)
                            .addComponent(yearlbl))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registrationNumberTx)
                            .addComponent(serialNumberTx)
                            .addComponent(modelNameTx)
                            .addComponent(yearTx)
                            .addComponent(ownerNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(SaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrationNumberlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrationNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNumberTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNumberlbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelNamelbl)
                    .addComponent(modelNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlbl)
                    .addComponent(yearTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerNamelbl)
                    .addComponent(ownerNameTx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        vehicleInfo.setManufacturingYear(yearTx.getText());
        vehicleInfo.setModelName(modelNameTx.getText());
        vehicleInfo.setOwnerName(ownerNameTx.getText());
        vehicleInfo.setRegistrationNumber(registrationNumberTx.getText());
        vehicleInfo.setSerialnNumber(serialNumberTx.getText());
       
        if (registrationNumberTx.getText().isEmpty() || ownerNameTx.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null, "Please enter required fields.", "Warning", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Vehicle Information Saved", "Success", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_SaveButtonActionPerformed

    private void registrationNumberTxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationNumberTxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrationNumberTxActionPerformed

    private void yearTxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_yearTxKeyPressed
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            yearTx.setEditable(false);
                 JOptionPane.showMessageDialog(null, "Please entry numbers only.", "Warning", JOptionPane.ERROR_MESSAGE);
        
        } else {
            yearTx.setEditable(true);
        }
    }//GEN-LAST:event_yearTxKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField modelNameTx;
    private javax.swing.JLabel modelNamelbl;
    private javax.swing.JTextField ownerNameTx;
    private javax.swing.JLabel ownerNamelbl;
    private javax.swing.JTextField registrationNumberTx;
    private javax.swing.JLabel registrationNumberlbl;
    private javax.swing.JTextField serialNumberTx;
    private javax.swing.JLabel serialNumberlbl;
    private javax.swing.JTextField yearTx;
    private javax.swing.JLabel yearlbl;
    // End of variables declaration//GEN-END:variables
}
